name: JR GitLint

on: [pull_request]

jobs:
  gitlint:

    runs-on: ubuntu-latest

    container:
      image: jorisroovers/gitlint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Gitlint
        run: gitlint --commits ${GITHUB_BASE_REF}..${GITHUB_HEAD_REF}
